apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret 
spec:
  template:
    spec:
      activeDeadlineSeconds: 600
      containers:
        - image: registry.redhat.io/openshift4/ose-tools-rhel8:v4.7
          command:
            - /bin/bash
            - -c
            - |
              set -e

              echo "$(oc whoami)"
              echo "$MY_POD_NAMESPACE"
              CLUSTER_NAME="$(oc get dns cluster -ojsonpath='{.spec.baseDomain}' | cut -d'.' -f1)"
              oc create secret generic cluster-name --from-literal=cluster_name=$CLUSTER_NAME -n $MY_POD_NAMESPACE

          imagePullPolicy: IfNotPresent
          name: secret 
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30

      
